global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@coraai.tech'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'cora-team'
  routes:
    - match:
        severity: critical
      receiver: 'cora-critical'
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'cora-warning'
      repeat_interval: 2h

receivers:
  - name: 'cora-team'
    email_configs:
      - to: 'admin@coraai.tech'
        send_resolved: true
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/webhook'
        send_resolved: true

  - name: 'cora-critical'
    email_configs:
      - to: 'admin@coraai.tech'
        send_resolved: true
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/critical'
        send_resolved: true

  - name: 'cora-warning'
    email_configs:
      - to: 'admin@coraai.tech'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service'] 