name: CI/CD Pipeline

on:
  push:
    branches: [ main, chore/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_e2e:
        description: "Run E2E tests"
        required: false
        default: "false"
        type: boolean
      cora_base_url:
        description: "Base URL for E2E (e.g., https://coraai.tech)"
        required: false
        default: "https://coraai.tech"
      e2e_timeout:
        description: "E2E timeout seconds"
        required: false
        default: "10"

jobs:
  baseline:
    name: Baseline (gated tests off)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install core test tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Install deps (if present)
        run: |
          python -m pip install --upgrade pip
          [[ -f requirements.txt ]] && pip install -r requirements.txt || true
          [[ -f requirements-dev.txt ]] && pip install -r requirements-dev.txt || true

      - name: Run baseline tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          TZ: "UTC"
          PYTHONPATH: "."
          CORA_E2E: "0"
          CORA_DB_TESTS: "0"
          CORA_DASH_TESTS: "0"
          CORA_SALES_TESTS: "0"
        run: |
          set -e
          mkdir -p .ci/empty-tests
          set +e
          pytest -q .ci/empty-tests
          ec=$?
          if [ "$ec" -eq 5 ]; then
            echo "No tests collected (baseline) — treating as success"
            exit 0
          fi
          exit $ec

  e2e:
    name: E2E (manual, opt-in)
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug E2E inputs
        run: |
          echo "event=${{ github.event_name }}"
          echo "run_e2e=${{ github.event.inputs.run_e2e }}"
          echo "cora_base_url=${{ github.event.inputs.cora_base_url }}"
          echo "e2e_timeout=${{ github.event.inputs.e2e_timeout }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install core test tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Install deps (if present)
        run: |
          python -m pip install --upgrade pip
          [[ -f requirements.txt ]] && pip install -r requirements.txt || true
          [[ -f requirements-dev.txt ]] && pip install -r requirements-dev.txt || true

      - name: Run E2E smoke tests
        if: ${{ github.event.inputs.run_e2e == 'true' }}
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          TZ: "UTC"
          PYTHONPATH: "."
          CORA_E2E: "1"
          CORA_BASE_URL: "${{ github.event.inputs.cora_base_url }}"
          E2E_TIMEOUT: "${{ github.event.inputs.e2e_timeout }}"
          GIT_SHA: "${{ github.sha }}"
          # keep all other gates off by default for E2E
          CORA_DB_TESTS: "0"
          CORA_DASH_TESTS: "0"
          CORA_SALES_TESTS: "0"
        run: |
          set -e
          echo "GIT_SHA=$GIT_SHA"
          pytest -q tests/test_final_system.py -rA --maxfail=1
