name: Monitoring Postcheck
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # 18:00Z daily

jobs:
  postcheck:
    runs-on: ubuntu-latest
    env:
      PROD_HOST: ${{ secrets.PROD_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
    steps:
      - name: Validate secrets
        shell: bash
        run: |
          test -n "$PROD_HOST" || (echo "PROD_HOST missing" && exit 1)
          test -n "$PROD_SSH_USER" || (echo "PROD_SSH_USER missing" && exit 1)
          test -n "$PROD_SSH_KEY" || (echo "PROD_SSH_KEY missing" && exit 1)

      - name: SSH → service & health checks (Linux)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -euo pipefail
            echo "1) Ensure cora.service is active"
            systemctl is-active --quiet cora.service || { systemctl status cora.service || true; exit 2; }
            echo "2) Recent logs exist for cora.service (last 15m)"
            if ! journalctl -u cora.service --since "-15 min" --no-pager | head -n 1 | grep -q . ; then
              echo "No recent journal entries for cora.service"; exit 3;
            fi
            echo "3) Local HTTP health checks"
            set +e
            H1=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/health)
            H2=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/api/status)
            set -e
            echo "health: $H1  status: $H2"
            [ "$H1" = "200" ] || { echo "/health not 200"; exit 4; }
            [ "$H2" = "200" -o "$H2" = "401" ] || { echo "/api/status not 200/401"; exit 5; }
            echo "Postcheck OK (service active, logs fresh, endpoints healthy)"
