name: Secrets Scan
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install detect-secrets
        run: pip install detect-secrets
      - name: Run detect-secrets against baseline
        run: |
          detect-secrets scan --baseline .secrets/.secrets.baseline
          detect-secrets audit --report .secrets/.secrets.baseline || true
          # Fail if new secrets are detected (diff against baseline)
          detect-secrets scan > .secrets/scan.json
          python - <<'PY'
import json, sys
with open('.secrets/scan.json') as f:
    data=json.load(f)
if data.get('results'):
    print('Potential secrets detected; please audit and update baseline if they are false positives.')
    sys.exit(1)
print('No new secrets detected.')
PY

